In [1]:
## numpy 矩阵运算

from numpy import *
eye(15) # eye(num) 生成对角矩阵

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [3]:
## NumPy 最重要的一个特点是其 N 维数组对象 ndarray
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
## 多维
import numpy as np
b = np.array([[1,2,3],[2,3,4]])
print(b)


[[1 2 3]
 [2 3 4]]


In [10]:
## 多维
import numpy as np
c = np.array([1,2,3,4,5,6],ndmin=2)
print(c)


[[1 2 3 4 5 6]]


In [15]:
### 调整维度
import numpy as np
d = np.array([[1,2,3],[2,3,4]])
d.shape=(3,2)
print(d)


[[1 2]
 [3 2]
 [3 4]]


In [22]:
## ndarray 数组除了可以使用底层 ndarray 构造器来创建外，也可以通过以下几种方式来创建。
### 不初始化创建
import numpy as np
e = np.empty([3,2],dtype=int)
print(e)

[[1 2]
 [3 2]
 [3 4]]


In [26]:
## 0填充
import numpy as np
f = np.zeros(5)
print(f)

## 1填充
g = ones([2,3])
print(g)


[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
import numpy as np
## 将列表转为ndarray
list = [1,2,3]
adarray1 = np.asarray(list)
print(adarray1)
## 将元组庄伟ndarray
turple1 = (1,4,5)
list2 = np.asarray(turple1)
print(list2)
## 将元组列表转为ndarray
list2 = [(1,2,3),(3,4)]
adarray2 = np.asarray(list2)
print(adarray2)


[1 2 3]
[1 4 5]
[(1, 2, 3) (3, 4)]


In [30]:
## 如何从数值范围创建数组。
import numpy as np
adarray3 = np.arange(2,5)
print(adarray3)


[2 3 4]


In [2]:
## ndarray对象的内容可以通过索引或切片来访问和修改
import numpy as np
adarray4 = np.arange(10)
s = slice(2,7,1)
print(adarray4)
print(adarray4[s])

b = adarray4[2:7:2]
print(b)


##
adarray5 = np.arange(20).reshape(4,5)
print(adarray5)
print(adarray5[:,[1,2]]) # :代表所有行，列表代表所选的列

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[2 4 6]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]]


In [36]:
## 广播机制
### 广播(Broadcast)是 numpy 对不同形状(shape)的数组进行数值计算的方式， 对数组的算术运算通常在相应的元素上进行。

import numpy as np

a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print (c)

### 当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制。如：

a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([0,1,2])
print(a + b)


[ 10  40  90 160]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [42]:
## 迭代输出（鸡肋）
import numpy as np
a = np.array([[1,4],[2,3]])
print(a)
print(a.T) # 转置
## 迭代输出
for x in np.nditer(a):
    print(x,end=" ")

[[1 4]
 [2 3]]
[[1 2]
 [4 3]]
1 4 2 3 

In [54]:
## 数组操作
### reshape
import numpy as np
a = np.arange(10)
print(a)

print(a.reshape(2,5))
### 增加元素
a = np.array([[1,2,3],[4,5,6]])
print(a)
print('\n')
print(np.append(a,[7,8,9]))
print(np.append(a,[[7,8,9]],axis=0))
print(np.append(a,[[5,5,5],[7,8,9]],axis=1))

### 去除重复值
a = np.array([1,2,3,3,4,2,1])
print(a)
print(np.unique(a))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 2 3]
 [4 5 6]]


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]
[1 2 3 3 4 2 1]
[1 2 3 4]


In [ ]:
### 位运算、字符串函数

In [55]:
### 数学函数
# eg:sin
import numpy as np
a = np.array([1,2,3,4])
print(np.sin(a))


[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [56]:
## 算术函数
a = np.array([1,2,3])
b = np.array([2,3,4])
print(a+b)
print(a*b)

[3 5 7]
[ 2  6 12]


In [62]:
## 统计函数

a = np.array([1,2,3,4,3])
print(np.amin(a))
print(np.median(a))
print(np.mean(a))
print(np.std(a))
print(np.var(a))

1
3.0
2.6
1.019803902718557
1.0400000000000003


#### np.bincount(y) ：
统计类别标签：在机器学习中，尤其是分类问题中，可以使用 np.bincount(y) 来快速统计每个类别的样本数量。
* 输入：np.bincount(y) 需要一个一维的非负整数数组 y 作为输入。
* 输出：返回一个数组，其中第 i 个元素表示数字 i 在输入数组 y 中出现的次数。

In [69]:
## 排序、条件筛选函数
### where numpy.where() 函数返回输入数组中满足给定条件的元素的索引。
a = np.array([1,2,3,4,3])
y = np.where(a>2)
print(y)
print(a[y])

### numpy.extract() 函数根据某个条件从数组中抽取元素，返回满条件的元素。
a = np.array([1,2,3,4,3])
condition = np.mod(a,2) == 0
print(condition)
print(np.extract(condition,a))


(array([2, 3, 4]),)
[3 4 3]
[False  True False  True False]
[2 4]


In [88]:
## =简单赋值是副本。
### 简单的赋值不会创建数组对象的副本。 相反，它使用原始数组的相同id()来访问它
a = np.arange(6)
print(a)
print(id(a))

b = a
b.shape=(2,3)
print(b)
print(id(b))
print(a)
### 视图，浅拷贝.该方法创建的新数组的维数变化不会改变原始数据的维数。
c = np.arange(6)
d = c.view()
print(c)
print(id(c))
d.shape=(2,3)
print(d)
print(id(d))
### 副本，深拷贝
print('\n')
print(d)
e = d.copy()
print(e)
e[1][0]=2 ## 不改变原先数据。
print(e)
print(e is d)
print(d)

[0 1 2 3 4 5]
140317418395968
[[0 1 2]
 [3 4 5]]
140317418395968
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
140317418395808
[[0 1 2]
 [3 4 5]]
140317418393728


[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [2 4 5]]
False
[[0 1 2]
 [3 4 5]]
